In [ ]:
#Import Libraries
import numpy as np
import pandas as pd

In [ ]:
#Upload Dataset
df=pd.read_csv('/content/ETH-BTC-USD.csv')

In [ ]:
df.head()

Date        Open        High         Low       Close   Adj Close  \
0  11/14/2018  206.533997  207.044998  174.084000  181.397003  181.397003   
1  11/15/2018  181.899002  184.251007  170.188995  180.806000  180.806000   
2  11/16/2018  180.865005  181.350006  173.126007  175.177002  175.177002   
3  11/17/2018  175.360001  175.850998  172.869003  174.001007  174.001007   
4  11/18/2018  174.175003  179.151993  174.175003  177.067001  177.067001   

         Volume  Currency  
0  2.595330e+09  Etherium  
1  2.638410e+09  Etherium  
2  2.015330e+09  Etherium  
3  1.832800e+09  Etherium  
4  1.810920e+09  Etherium

In [ ]:
data=df.drop(['Date','Adj Close'],axis=1) #remove unwanted parameters

In [ ]:
data.head()

Open        High         Low       Close        Volume  Currency
0  206.533997  207.044998  174.084000  181.397003  2.595330e+09  Etherium
1  181.899002  184.251007  170.188995  180.806000  2.638410e+09  Etherium
2  180.865005  181.350006  173.126007  175.177002  2.015330e+09  Etherium
3  175.360001  175.850998  172.869003  174.001007  1.832800e+09  Etherium
4  174.175003  179.151993  174.175003  177.067001  1.810920e+09  Etherium

In [ ]:
#segregating dataset into x and y axis(dependent and independent)
x=data.drop(['Currency'],axis=1)
y=data['Currency']

In [ ]:
#spliting training set and testing set
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8)

Decision Tree Algorithm

In [ ]:
from sklearn.tree import DecisionTreeClassifier
treeclassifier=DecisionTreeClassifier()

In [ ]:
treeclassifier.fit(x_train,y_train) #Training MLM

DecisionTreeClassifier()

In [ ]:
tree_prediction=treeclassifier.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix
ac= accuracy_score(y_test,tree_prediction)
cm=confusion_matrix(y_test,tree_prediction)

In [ ]:
ac #with Decision Tree Algorithm accuracy received is 99%

0.9945280437756497

In [ ]:
cm

array([[366,   3],
       [  1, 361]])

Random Forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier
Forest_classifier=RandomForestClassifier()

In [ ]:
Forest_classifier.fit(x_train,y_train)

RandomForestClassifier()

In [ ]:
prediction=Forest_classifier.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix
ac= accuracy_score(y_test,prediction)
cm=confusion_matrix(y_test,prediction)

In [ ]:
ac

0.9931600547195623

In [ ]:
cm

array([[365,   4],
       [  1, 361]])

KNN Algorithm

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
KNN=KNeighborsClassifier(n_neighbors=5)

In [33]:
KNN.fit(x_train,y_train)

KNeighborsClassifier()

In [38]:
KNN_prediction=KNN.predict(x_test)

In [39]:
from sklearn.metrics import accuracy_score,confusion_matrix
ac= accuracy_score(y_test,KNN_prediction)
cm=confusion_matrix(y_test,KNN_prediction)

In [40]:
cm

array([[256, 113],
       [111, 251]])

In [41]:
ac

0.6935704514363885